### ISSUE TITLE
Should not create backup config files

### ISSUE THREAD

**Issue by jabl** [CSCfi/ansible-ferm-firewall#2]
Since ferm includes ALL files under the directory included in /etc/ferm.conf, it will also include the ansible backup files.

**Comment by tiggi** [comment]
did some stracing on io:
open("/etc/ferm.conf", O_RDONLY)        = 5
open("/etc/ferm/ferm.d/05_ssh.conf", O_RDONLY) = 6
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=21377, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=21378, si_status=0, si_utime=0, si_stime=0} ---
open("/etc/ferm/ferm.d/nat.conf", O_RDONLY) = 6

[root@io-install ferm.d]# ls /etc/ferm/ferm.d/
05_ssh.conf  05_ssh.conf.2016-07-18@14:27:48~  nat.conf
[root@io-install ferm.d]# 

not reproducible on io.

**Comment by jabl** [comment]
Yup, no fault here, closing.
