### ISSUE TITLE
/etc/ferm/ferm.conf is unmanaged

### ISSUE THREAD

**Issue by vosdev** [CSCfi/ansible-ferm-firewall#8]
Installing ferm on my Ubuntu 18.04 or Debian 9.8 systems leaves me with a default /etc/ferm/ferm.conf (which seems reasonable :-) )

**It contains firewall rules** as well. These get mixed with your own rules. This file should be fully managed instead of only enforcing the `@include` line.

Second, why is there a difference between redhat and non-redhat systems regarding the ferm.d directory?
With this role RedHat systems are to use `/etc/ferm/ferm.d`  and non-RedHat systemd get to use `/etc/ferm.d`. I don't see any reason for this. By default, ferm on Ubuntu (18.04) even comes with a `/etc/ferm/ferm.d` dir and an `@include ferm.d;` config option.

Example of `/etc/ferm/ferm.conf` after installing on Ubuntu 18.04:
```
# -*- shell-script -*-
#
#  Configuration file for ferm(1).
#
domain (ip ip6) {
    table filter {
        chain INPUT {
            policy DROP;

            # connection tracking
            mod state state INVALID DROP;
            mod state state (ESTABLISHED RELATED) ACCEPT;

            # allow local packet
            interface lo ACCEPT;

            # respond to ping
            proto icmp ACCEPT;

            # allow IPsec
            proto udp dport 500 ACCEPT;
        @if @eq($DOMAIN, ip) {
          proto (esp ah) ACCEPT;
        } @else {
          proto (esp) ACCEPT;
        }

            # allow SSH connections
            proto tcp dport ssh ACCEPT;
        }
        chain OUTPUT {
            policy ACCEPT;

            # connection tracking
            #mod state state INVALID DROP;
            mod state state (ESTABLISHED RELATED) ACCEPT;
        }
        chain FORWARD {
            policy DROP;

            # connection tracking
            mod state state INVALID DROP;
            mod state state (ESTABLISHED RELATED) ACCEPT;
        }
    }
}

@include ferm.d/;
```

And on Debian 9.8:
```
# -*- shell-script -*-
#
#  Configuration file for ferm(1).
#

table filter {
    chain INPUT {
        policy DROP;

        # connection tracking
        mod state state INVALID DROP;
        mod state state (ESTABLISHED RELATED) ACCEPT;

        # allow local packet
        interface lo ACCEPT;

        # respond to ping
        proto icmp ACCEPT;

        # allow IPsec
        proto udp dport 500 ACCEPT;
        proto (esp ah) ACCEPT;

        # allow SSH connections
        proto tcp dport ssh ACCEPT;
    }
    chain OUTPUT {
        policy ACCEPT;

        # connection tracking
        #mod state state INVALID DROP;
        mod state state (ESTABLISHED RELATED) ACCEPT;
    }
    chain FORWARD {
        policy DROP;

        # connection tracking
        mod state state INVALID DROP;
        mod state state (ESTABLISHED RELATED) ACCEPT;
    }
}

# IPv6:
#domain ip6 { 
#    table filter {
#        chain INPUT {
#            policy ACCEPT;
#            # ... 
#        }
#        # ...
#    }
#}
```

**Comment by martbhell** [comment]
> Installing ferm on my Ubuntu 18.04 or Debian 9.8 systems leaves me with a default /etc/ferm/ferm.conf (which seems reasonable :-) )
> 
> **It contains firewall rules** as well. These get mixed with your own rules. This file should be fully managed instead of only enforcing the `@include` line.
> 
> Second, why is there a difference between redhat and non-redhat systems regarding the ferm.d directory?
> With this role RedHat systems are to use `/etc/ferm/ferm.d` and non-RedHat systemd get to use `/etc/ferm.d`. I don't see any reason for this. By default, ferm on Ubuntu (18.04) even comes with a `/etc/ferm/ferm.d` dir and an `@include ferm.d;` config option.

Hello!

Because this is how it was when this role was written, when Ubuntu 15 or 16 was still the latest :)
To me it sounds like they are both the same now and this role can be further improved.
Sorry about the delay, I don't use this role myself anymore. Hoping for other contributions.

**Comment by vosdev** [comment]
I have made several changes to the role as you can see in my fork:

https://github.com/Nachtmerrie/ansible-ferm-firewall

I am looking to improve it further but for now it does a great job scaling my firewall for me.


Are you now using something else to manage your firewall?

**Comment by martbhell** [comment]
Cool!
Maybe there's some benefit we could get from your improvements too.
I changed group at the company and we use puppet and firewalld there instead... I don't recommend that change :)
But recently I looked at nft in Debian 10 and those rules look quite similar to ferm.
Pinging @VilleS1 who's currently using this role here at CSCfi :)

**Comment by vosdev** [comment]
I plan on making some centos VMs to also test my changes on a redhat family machine. And thanks for reminding me about buster.  A change I made will break on buster (making sure iptables is installed)

**Comment by VilleS1** [comment]
I merged your fork with us. There were a lot of patches. The tests don't pass and there may be other issues why we need to go back but we'll see.

**Comment by vosdev** [comment]
@VilleS1 

### I remember making one breaking change:
**I removed the required `;` at the end of every rule in your variable config. The `;` has been moved to the template.**



Some noticable changes include:

Rule group name no longer requires .conf
```diff
ferm_rules:
-  01-policies.conf:
+  01-policies:
```

/etc/ferm/ferm.d is completely managed. Every run it will list the contents of /etc/ferm/ferm.d and compare them to the rule groups you want the server to have.

example: 
If you have a node in a `lxd` group and that has the following configuration in group_vars/lxd.yaml:
```yaml
ferm_rules:
  50-lxd-mgmt:
    - chain: INPUT
      domains: [ip, ip6]
      rules:
        - rule: proto tcp dport ( 8443 ) saddr @ipfilter(( 2001:db8:20::d1 2001:db8:20::d2 )) ACCEPT
```
A file called `/etc/ferm/ferm.d/50-lxd-mgmt.conf` will be created.
If you remove the node from the `lxd` group and run the role again, `/etc/ferm/ferm.d/50-lxd-mgmt.conf` will be removed.




Regardless, thanks for the merge! I will continue to improve it and will rsend you guys a PR when I do so.

**Comment by VilleS1** [comment]
Nachtmerrie, we decided to unmerge your changes. They look good but I think for us at this point we don't want to do the work required the change our systems with the new code. If somebody starts from scratch I think your fork is the one to start with and our code/fork should be considered old and obsolete.

**Comment by VilleS1** [comment]
Everything is now using /etc/ferm/ferm.d and /etc/ferm/ferm.conf

**Comment by VilleS1** [comment]
So closing this issue.
